name: figma-plugin
channels:
  - defaults
dependencies:
  - python=3.11
  - pip
  - portaudio
  - pip:
    - fastapi
    - uvicorn
    - openai
    - python-dotenv
    - pyobjc-framework-Quartz
    - pyobjc-framework-Cocoa
    - SpeechRecognition
    - pyaudio
    - deepgram-sdk
    - faster-whisper
    - soundfile
    - pyautogui
    - websocket-client
    - websockets